entorno: Bruno
replicaCount: 1

image:
  repository: ghcr.io/bruno-practicas/tfm-ai
  tag: Bruno-latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull-secret

service:
  port: 80

ingress:
  host: bruno.helmcode.com
  certResolver: letsencrypt
