apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tfm-ai-api

resources:
  - https://raw.githubusercontent.com/FabioCubas101/tfm-ai-api/refs/heads/main/k8s/deployment.yaml
  - https://raw.githubusercontent.com/FabioCubas101/tfm-ai-api/refs/heads/main/k8s/service.yaml
  - https://raw.githubusercontent.com/FabioCubas101/tfm-ai-api/refs/heads/main/k8s/ingressroute.yaml
  - https://raw.githubusercontent.com/FabioCubas101/tfm-ai-api/refs/heads/main/k8s/middleware.yaml

patches:
  - target:
      kind: IngressRoute
      name: tfm-ai-api-http
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`bruno-api.helmcode.com`)"

  - target:
      kind: IngressRoute
      name: tfm-ai-api-https
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`bruno-api.helmcode.com`)"
