apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tfm-ai
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-tfm-ai
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tfm-ai
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tfm-ai
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tfm-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
