apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.app.name }}-https-redirect
  namespace: {{ .Values.app.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"
